# Generated by Django 5.2.7 on 2025-10-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadSysV1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
