# Generated by Django 5.2.7 on 2025-10-27 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadSysV1', '0002_fileupload_feedback_fileupload_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploadSysV1.registration'),
        ),
    ]
